export const TV_CHANNELS = [
  {
    key: 'netflix',
    label: 'Netflix',
    logoSrc: 'https://commons.wikimedia.org/wiki/Special:FilePath/Netflix%202015%20logo.svg',
    subtitle: 'Originals',
    logoClassName: '',
  },
  {
    key: 'primeVideo',
    label: 'Prime Video',
    logoSrc: 'https://commons.wikimedia.org/wiki/Special:FilePath/Amazon%20Prime%20Video%20logo%20(2022).svg',
    subtitle: 'Prime Originals',
    logoClassName: '',
  },
  {
    key: 'hulu',
    label: 'Hulu',
    logoSrc: 'https://commons.wikimedia.org/wiki/Special:FilePath/Hulu%20logo%20(2017).svg',
    subtitle: 'US Hits',
    logoClassName: '',
  },
  {
    key: 'disneyPlus',
    label: 'Disney+',
    logoSrc: 'https://commons.wikimedia.org/wiki/Special:FilePath/Disney%2B%202024.svg',
    subtitle: 'Family',
    logoClassName: '',
  },
  {
    key: 'appleTVPlus',
    label: 'Apple TV+',
    logoSrc: 'https://commons.wikimedia.org/wiki/Special:FilePath/Apple%20TV%20Plus%20Logo.svg',
    subtitle: 'Prestige',
    logoClassName: 'invert brightness-200',
  },
  {
    key: 'peacock',
    label: 'Peacock',
    logoSrc: 'https://commons.wikimedia.org/wiki/Special:FilePath/NBCUniversal%20Peacock%20Logo.svg',
    subtitle: 'NBCU',
    logoClassName: '',
  },
  {
    key: 'paramountPlus',
    label: 'Paramount+',
    logoSrc: 'https://commons.wikimedia.org/wiki/Special:FilePath/Paramount%2B%20logo.svg',
    subtitle: 'CBS / Trek',
    logoClassName: '',
  },
  {
    key: 'hbo',
    label: 'HBO',
    logoSrc: 'https://commons.wikimedia.org/wiki/Special:FilePath/HBO%20logo.svg',
    subtitle: 'Premium',
    logoClassName: 'invert brightness-200',
  },
  {
    key: 'cartoonNetwork',
    label: 'Cartoon Network',
    logoSrc: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cartoon%20Network.svg',
    subtitle: 'Classic Toons',
    logoClassName: '',
  },
  {
    key: 'nickelodeon',
    label: 'Nickelodeon',
    logoSrc: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nickelodeon%20Logo.svg',
    subtitle: 'Nicktoons',
    logoClassName: '',
  },
  {
    key: 'hungama',
    label: 'Hungama TV',
    logoSrc: 'https://commons.wikimedia.org/wiki/Special:FilePath/Hungama%20TV.svg',
    subtitle: 'Dubbed Anime',
    logoClassName: '',
  },
  {
    key: 'disneyChannel',
    label: 'Disney Channel',
    logoSrc: 'https://commons.wikimedia.org/wiki/Special:FilePath/2024%20Disney%20Channel%20text%20logo.svg',
    subtitle: 'Youth Favorites',
    logoClassName: 'invert brightness-200',
  },
]
