export const TV_SHELVES = [
  { key: 'trending', label: 'Trending Now', kind: 'trending' },
  { key: 'topRated', label: 'Top Rated of All Time', kind: 'discover' },
  { key: 'popular', label: 'Popular Right Now', kind: 'discover' },
  { key: 'hindi', label: 'Hindi Originals', kind: 'discover' },
  { key: 'animation', label: 'Animated TV', kind: 'discover' },
  { key: 'actionAdventure', label: 'Action & Adventure', kind: 'discover' },
  { key: 'crime', label: 'Crime Stories', kind: 'discover' },
  { key: 'family', label: 'Family & Kids', kind: 'discover' },
  { key: 'sciFiFantasy', label: 'Sci-Fi & Fantasy', kind: 'discover' },
  { key: 'documentary', label: 'Documentary', kind: 'discover' },
  { key: 'reality', label: 'Reality', kind: 'discover' },
  { key: 'talk', label: 'Talk', kind: 'discover' },
  { key: 'news', label: 'News', kind: 'discover' },
  { key: 'soap', label: 'Soap', kind: 'discover' },
  { key: 'western', label: 'Western', kind: 'discover' },
  { key: 'japanese', label: 'Japanese Hits', kind: 'discover' },
  { key: 'korean', label: 'Korean Hits', kind: 'discover' },
  { key: 'spanish', label: 'Spanish Favorites', kind: 'discover' },
]
