export const TV_SHELVES = [
  { key: 'trending', label: 'Trending Now', kind: 'trending' },
  { key: 'netflix', label: 'Netflix Originals', kind: 'discover' },
  { key: 'primeVideo', label: 'Prime Video Picks', kind: 'discover' },
  { key: 'hulu', label: 'Hulu Originals', kind: 'discover' },
  { key: 'disneyPlus', label: 'Disney+ Favorites', kind: 'discover' },
  { key: 'appleTVPlus', label: 'Apple TV+ Originals', kind: 'discover' },
  { key: 'peacock', label: 'Peacock Picks', kind: 'discover' },
  { key: 'paramountPlus', label: 'Paramount+ Selects', kind: 'discover' },
  { key: 'hbo', label: 'HBO Classics', kind: 'discover' },
  { key: 'cartoonNetwork', label: 'Cartoon Network Classics', kind: 'discover' },
  { key: 'nickelodeon', label: 'Nickelodeon Throwbacks', kind: 'discover' },
  { key: 'hungama', label: 'Hungama Anime', kind: 'discover' },
  { key: 'disneyChannel', label: 'Disney Channel Favorites', kind: 'discover' },
  { key: 'englishThrowbacks', label: 'English Throwbacks', kind: 'discover' },
  { key: 'ninetyKids', label: '90s Kids Memories', kind: 'discover' },
  { key: 'topRated', label: 'Top Rated of All Time', kind: 'discover' },
  { key: 'popular', label: 'Popular Right Now', kind: 'discover' },
  { key: 'hindi', label: 'Hindi Originals', kind: 'discover' },
  { key: 'animation', label: 'Animated TV', kind: 'discover' },
  { key: 'actionAdventure', label: 'Action & Adventure', kind: 'discover' },
  { key: 'crime', label: 'Crime Stories', kind: 'discover' },
  { key: 'family', label: 'Family & Kids', kind: 'discover' },
  { key: 'sciFiFantasy', label: 'Sci-Fi & Fantasy', kind: 'discover' },
  { key: 'documentary', label: 'Documentary', kind: 'discover' },
  { key: 'reality', label: 'Reality', kind: 'discover' },
  { key: 'talk', label: 'Talk', kind: 'discover' },
  { key: 'news', label: 'News', kind: 'discover' },
  { key: 'soap', label: 'Soap', kind: 'discover' },
  { key: 'western', label: 'Western', kind: 'discover' },
  { key: 'japanese', label: 'Japanese Hits', kind: 'discover' },
  { key: 'korean', label: 'Korean Hits', kind: 'discover' },
  { key: 'spanish', label: 'Spanish Favorites', kind: 'discover' },
]
